version: '3'
services:
  web:
    tty: true
    stdin_open: true
    build: .
    command: php -S 0.0.0.0:8001
    volumes:
      - ./src/:/code
    ports:
      - "8001:8001"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
         - .pgdata:/var/lib/postgresql/data
